### ISSUE TITLE
Major issues getting the system online.

### ISSUE THREAD

**Issue by kurtisa727** [kizniche/Mycodo-custom#5]
I'm just unable to get the program to operate the way its designed.

First and foremost, the hydroponics system you showcased on https://kylegabriel.com/projects/2020/06/automated-hydroponic-system-build.html is the most comprehensive and thought out systems I have ever seen. 
I pretty much just copied the parts list and ordered the items. I needed off Amazon and other places from the hydroponics article. 

I'm not the smartest person in the world but I'm a former U.S. Army Aviation Mechanic, I worked on attack helicopter weapon systems as a mechanic/ electrician. This has me stumped. 

I'm running a Raspberry pi 4 with the latest version of Mycodo, and the required Raspberry Pi operating system (full desktop). 

I pretty much just copied the parts list and ordered the items. I needed off Amazon and other places from the very detailed hydroponics article. 

I put everything together, actually pretty much the same as your article and schematics and went through the different inputs and outputs and added some of the controls, coding for conditions, etc. I'm getting readings from my PH sensor, water temp sensor, EC/ PPM Sensor, humidity, air temp, vapor press def., Digital to analog converter is working

**1# The first issue (Would not let me change pump address, new pumps added had new address instead of default?)

....occurred when I was trying to set the iC2 addresses for the peristaltic pumps, I have seven pumps to assign. (Two for PH and five for nutrients/ EC level). When I plugged Pump #1 into the system and ran the detect command, it detected the pump at 41. I attempted to use the sequence of commands to change the iC2 address to something else and it gave me errors. I then went through the MyCodo set up for the pump and it even dispensed the calibration amounts up command. 

I then plugged Pump #2 in and entered the detect command. The system detected the pump at a different address, this time 65. I then repeated this sequence for five pumps and they all had different addresses upon being plugged in. All of the calibration commands worked on four of the five. When I plugged in Pump #6, it had the same address as Pump 5, and the system would not let me change the iC2 Address in Mycodo or via command prompt. 

**2# The second issue (LCD Screen will not work)

The generic LCD Screen is lit up but blank and occasionally it has some gibberish on it. 

**3# Third Issue (Will not follow commands to monitor PH and EC levels)

I followed the tutorial online word for word and could not get the system to work for me as intended. 

**4# Fourth Issue (Power Distribution Box not Working)

I do not believe the box is getting a signal from the computer

I'm stumped on this one, I'm hoping I do not have a faulty computer. Any assistance would be greatly appreciated.

**Comment by kizniche** [comment]
Hi @kurtisa727. Please use the [forum](https://forum.radicaldiy.com) for this kind of discussion. This also isn't the Mycodo repository (it is at https://github.com/kizniche/Mycodo). Thanks
